### ISSUE TITLE
[BUG] Connector Swagger Endpoint in latest release unusable

### ISSUE THREAD

**Issue by pajoma** [nmshd/feedback#12] opened 2022-01-07 08:24 UTC
**Describe the bug**
I reinstalled the connector within the Azure Cloud yesterday (switching the Mongo Backend). Since then, the Swagger UI doesn't load anymore. Rapidocs and API itself is fine. 

**To Reproduce**
1. Go to http://..connector../docs/swagger/
2. Timeout while loading

**Expected behavior**
Swagger UI should load

**Screenshots**
The culprit seems to be the favicon? Here's my network analysis from firefox. HTML Code can be analysed, the JS-dependencies are not loaded. 

![grafik](https://user-images.githubusercontent.com/92156/148514354-fcd9164f-5791-422e-a550-7b2d052dea80.png)

**Environment**
Firefox

**Comment by stnmtz** [comment] 2022-01-07 10:08
Hi there,

thanks for the input! I actually cannot reproduce this issue with Connector Image "ghcr.io/nmshd/connector:latest" and Firefox 95.0.2 (or Chrome). 

I cannot see the favicon blocking, as loading any image shouldn't block the whole site from appearing, least a missing favicon.

Could you check if you are running on the latest version of the Connector and Firefox? Could a Firefox Plugin/Addon, anti virus scanner or firewall blocking the request?

Cheers

**Comment by stnmtz** [comment] 2022-01-14 11:02
Hi @pajoma,

did you have a change to look further into your favicon issue? Would it be possible to send us more information in order to reproduce?
Otherwise we will close the issue soon as we cannot confirm it.

Best Regards

**Closed as completed** 2022-01-19 14:45 UTC
Labels: bug

**Comment by jkoenig134** [comment] 2022-01-19 14:53
Hi @pajoma!

with your additional resources we could fix the bug. A middleware we use augmented the content security policy with [upgrade-insecure-requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/upgrade-insecure-requests), which caused the browser to try to upgrade from https to http for loading additional resources. And since your Connector supports http only, those requests timed out.
You can use the updated [version 2.1.5](https://github.com/nmshd/cns-connector/pkgs/container/connector/13477257?tag=2.1.5) of the connector to fix it.
